...

diff --git a/.github/workflows/pr-comment-watcher.yml b/.github/workflows/pr-comment-watcher.yml
--- a/.github/workflows/pr-comment-watcher.yml
+++ b/.github/workflows/pr-comment-watcher.yml
@@ -41,12 +41,18 @@ jobs:
         if: ${{ steps.deploy-branch.outputs.NAME != '' }}
         id: push-current-branch-to-qa-branch
         run: |
-          echo "The value of NAME: ${{ steps.deploy-branch.outputs.NAME }}"
-          echo "pushing $CURR_BRANCH to $QA_ENV"
-
+          CURRENT_BRANCH=$(git branch --show-current)
           QA_BRANCH="${{ steps.deploy-branch.outputs.NAME }}"
 
-          git status
-          git branch
+          if [[ "$QA_BRANCH" == "master" ]]; then
+            echo "can't force push to master"
+            exit 1
+          fi
 
-          # git push --force origin "$CURR_BRANCH":"$QA_ENV"
+          if [[ "$QA_BRANCH" == "main" ]]; then
+            echo "can't force push to main"
+            exit 1
+          fi
+
+          echo "pushing $CURRENT_BRANCH to $QA_BRANCH"
+          #git push --force origin "$CURRENT_BRANCH":"$QA_BRANCH"
